### ISSUE TITLE
Order management commands

### ISSUE THREAD

**Issue by Fashew** [hummingbot/hummingbot#1691]
**Feature Suggestion**
The bot doesn't cover its positions well.  Inventory skew and hanging orders aren't sufficient.  This leaves bot users "naked" in positions when the market turns against them.  The point of market making is to remain "price agnostic".  This means always covering your positions.

I would like to see a market order trigger feature.

Say I have a 1.2% bid/ask spread.  The "prevailing" spread is .4%.  (This is typical of our markets.)

My ask gets executed.  The bot immediately makes a market buy order or, in case there is no market order function on the exchange, a limit order for the amount I just sold it for.   This would, in a perfect world guarantee a profit of .8%.    I have been doing this manually for trades that execute with good results.

You may be asking "What about when large price swings happen?"  This strategy may limit losses.  You may cover your position for what you sold it for, but you won't be on the wrong side of a runaway price movement.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd17jd) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
Revised as **Order management commands** and added to Backlog

Add new commands that allow users to place and cancel orders from the CLI:
- `place`
    - side (buy/sell)
    - type (limit/market)
    - amount
- `cancel`
    - orderID

**Comment by phbrgnomo** [comment]
This trigger (send market orders when one side is filled) could have a setting to consider a `price slippage % limit` of this market order if the market maker don't want his actions influencing the flow of the market.

Another issue is that if `hanging_orders` is enabled, it could create a situation where the bot would try to take his own limit order.

**Comment by Nullably** [comment]
From what I understand there are few feature requests from this ticket:

**From @Fashew**

* Auto position covering when possible for PMM 
  - The bot first needs to keep track of its exposure (the goal is to be market direction neutral), e.g. +1.5 ETH at 300 USDT price (bought  1.5 ETH)
  - When market moves in their favour (over pre defined percentage value), e.g. best bid price is now at 303, the bot sells 1.5 ETH back to the market (to get back to its neutral position)
  - 2 config parameters are needed for this - `position_covering_when_profitable` (a flag) and `position_covering_pct` (a percentage value)

Note: We should always use `limit` order for this, not `market` order (due to flaws of this type of order).

**From @mifeng**

* 2 commands for users to place and cancel orders (manually)

**From @phbrgnomo**

> `price slippage % limit` 

* I am not sure what you mean by this one

>  `hanging_orders`

* Agree, the bot should check to make sure it doesn't take it own orders

**Comment by Nullably** [comment]
@Fashew 
> My ask gets executed. The bot immediately makes a market buy order

When the ask order gets filled, if the bot immediately places a taker buy order, would you in a loss for this? 
When the ask order gets filled, this means the lower ask orders are all taken out, the next one would be at least equal or at higher price.

**Comment by phbrgnomo** [comment]
> When the ask order gets filled, if the bot immediately places a taker buy order, would you in a loss for this?

A loss can happen if there is too many competition (in high liquidity markets) and the order book is quickly refilled by other market makers in the direction of the orders flow:

For example, with an ask order at 1000 is filled, with the best ask now at 1003, By the time the bot calculate and send the information to take the best bid, other makers might have already been posting bids at 1001 and 1002, which would incur in a loss.

The bot should check first if the best bid is still inside the `position_covering_pct`. It would still be risky on a high trade volume market (like btc-usdt) due to high competition, but it could work fine on lower trade volume pairs.

> `price slippage % limit`

This could be needed depending on the `order_amount`. A big taker order could consume the price levels of the order book, signaling a trend to other traders and influence the order flow. Usually, this is something that market makers don't want to do.
This could be tied to a boolean trigger `limit_covering_slippage`.

> Agree, the bot should check to make sure it doesn't take it own orders

Maybe this option should be disabled if `hanging_orders_enabled` is true. Since the timing of covering the filled order is a big part of the strategy, adding another check could slow down the execution.

**Comment by Nullably** [comment]
> This could be needed depending on the order_amount. A big taker order could consume the price levels of the order book, signaling a trend to other traders and influence the order flow. Usually, this is something that market makers don't want to do.
This could be tied to a boolean trigger limit_covering_slippage.

Let's not consider this for now as it's unclear what actions the bot needs to take exactly. How big an order is considered big? If so, then what does the bot needs to do?

**Comment by Nullably** [comment]
> Maybe this option should be disabled if hanging_orders_enabled is true. Since the timing of covering the filled order is a big part of the strategy, adding another check could slow down the execution.

Let's make this feature not compatible with hanging orders, if both are set the bot shouldn't start market making and inform errors

**Comment by mifeng** [comment]
Given our focus on power users and developers building scripts and custom strategies, I don't think we should do this story. 

It would add more parameters to PMM for functionality that only some users want, which increases complexity for other users. In addition, we would need to spend time to test these new parameters and fix any bugs that arise.

Instead, I think we should make writing custom strategies easier and create simple examples that show users can place and create orders depending on the state of the market and their inventory.
