### ISSUE TITLE
[Feature] Logging when orders are below minimum order size

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#2004]
**Feature Suggestion**

Show in logs when an order cannot be created because the amount is below the exchange's minimum order size. We have this in some of our connectors and would be good idea to have it in all of them.

**Impact**

The users mentioned in this PR https://github.com/CoinAlpha/hummingbot/pull/1983 suggested to have a notification of some sort when the orders are not created because their orders are below the exchange's minimum size.

**Additional context**

For example in this screenshot, I enabled inventory skew. Looking at `Order Adjust %` and `Inventory Range`, the bot should be creating buy orders but with a very small order size. Since my unadjusted order amount is 0.05 which is already almost the minimum, the downsized buy orders are most likely not created because of the trade rule.

![](https://user-images.githubusercontent.com/50150287/86880594-7dfb7580-c11f-11ea-8e6d-f4b39490f5ff.png)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1d4k) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
If you edit the `conf_global.yml` file to change the minimum order size accepted by the bot, what happens is that, if you enter an `order_amount` lower than what is accepted by the exchange, there is no warning about that on the bot.

![Captura de tela 2020-09-06 10 20 47](https://user-images.githubusercontent.com/34484531/92955811-3c978700-f43c-11ea-9063-72aa989233be.png)

On the picture above, the order size was below the minimum accepted by the exchange, and since there was no warning, i took a long time to understand why my order wasn't being sent.

A warning on the log on the lines of 'Order size below minimum accepted by the exchange' would be enough.
