### ISSUE TITLE
Telegram stops accepting input after entering an invalid value to configs

### ISSUE THREAD

**Issue by AngeredZeus** [hummingbot/hummingbot#2139]
**Describe the bug**
When you mistype a configuration in the telegram input config command, it cannot recover without logging into the instance to manually fix the configuration. 
**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
Run pure mm strategy and connect telegram bot. Enter input with typo e.g. `config price_source_exchange test`
The bot will now print:
 `Invalid exchange, please choose value from {'coinbase_pro', 'kucoin', 'binance', 'kraken', 'dolomite', 'huobi', 'bamboo_relay', 'bitcoin_com', 'bittrex', 'radar_relay', 'liquid', 'eterbase'}`
It will not be able to respond from telegram anymore, and will wait for the correct value in the CLI e.g.
`Enter external price source exchange name >>>            `
**Screenshots**
![user making telegram typo](https://user-images.githubusercontent.com/3011525/89115100-2f0cdb80-d452-11ea-964f-10092e709fc2.PNG)
![CLI View](https://user-images.githubusercontent.com/3011525/89115128-6085a700-d452-11ea-826c-6b41aa4dbea0.PNG)
**Release version**
0.29.0

**Optional: your discord username:**
AngeredZeus

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak543) by [Unito](https://www.unito.io)

**Comment by sigit2306** [comment]
This issue seems to happen on a configuration that is a list type. 
Beside `config price_source_exchange` it also happens when you mistype a configuration in the telegram input config command, it cannot recover without logging into the instance to manually fix the configuration for `config market` and `config exchange`

**config market** 
![01](https://user-images.githubusercontent.com/12313129/89253970-3f86a700-d648-11ea-94fc-549f7af71480.png)
![03](https://user-images.githubusercontent.com/12313129/89253982-46151e80-d648-11ea-8962-47ef6ff2d2d6.png)
![04](https://user-images.githubusercontent.com/12313129/89254047-66dd7400-d648-11ea-91f5-505ef2969f82.png)
.
.
.
.
.
**config exchange**
![05](https://user-images.githubusercontent.com/12313129/89254074-73fa6300-d648-11ea-8141-a9ec3b474745.png)
![07](https://user-images.githubusercontent.com/12313129/89254081-778dea00-d648-11ea-8db0-057cb1667a92.png)

**Comment by AngeredZeus** [comment]
It also fails to handle it if you use for example ```config bid_spread 101``` and ```config order_levels 0``` in telegram on puremm strategies. So it wouldn't appear that it is just lists.

**Comment by AngeredZeus** [comment]
So I think I found the issue. 
When hummingbot handles telegram input:
https://github.com/CoinAlpha/hummingbot/blob/99dc58fdc2f9e56e65417d1a32e21af7b67f0c05/hummingbot/notifier/telegram_notifier.py#L135
It calls this function https://github.com/CoinAlpha/hummingbot/blob/99dc58fdc2f9e56e65417d1a32e21af7b67f0c05/hummingbot/client/hummingbot_application.py#L132
So basically all input from telegram is treated as a command.

So when it continuously tries to validate input from the CLI:
https://github.com/CoinAlpha/hummingbot/blob/6e825b1c6fd6a9e9d9b89b9bf1effccbeb4bacc7/hummingbot/client/command/create_command.py#L111
it isn't getting anything passed from telegram since telegram can only input commands and not respond to prompts
Still not entirely sure the best way to fix this.
