### ISSUE TITLE
[Feature] Backtesting spec

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot#2446]
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakg96) by [Unito](https://www.unito.io)

**Comment by jonatasfreitasv** [comment]
#2816

**Comment by jonatasfreitasv** [comment]
Have why to open more about private backtesting tool akka "HummingSim"? for community try to make a open HummingBot backtester?

**Comment by KaneM2** [comment]
I'd also be interested in the above

**Comment by yogisha52** [comment]
It would be nice if the backtesting code is open source, so that we can run backtesting with the data we have. tick by tick is hard to get but candle data can be download to get a rough approximate. I can help write a randomized data generator based on the high, low, volume etc for each candle interval. I dont mind having a payed service that uses the original data set toom but that still doesnt mean the backtest source code cant be opensource.

**Comment by mifeng** [comment]
There are already open source Python-based backtesting engines for stocks like https://www.backtrader.com and https://github.com/quantopian/zipline. However, since those tools are in Python, backtesting is slow. I think it's possible to build an integration between them and Hummingbot if someone from the community is interested in drafting a spec. I would recommend `backtrader` since we have some familiarity with it and can give feedback on it.

Note that we are launching a premium service called Hummingbot Pro (Cython-based backtesting engine + order book data, accessible via API or web app) early next year.
