### ISSUE TITLE
[Feature] Option against trending drops

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [hummingbot/hummingbot#2451]
**Impact**
The problem arises, as also mentioned in the documentation, when the market shows a trend. This problem also occurs with strong drops in the price. In picture 1 you can see that even if you have activated hanging orders, the effective spread is reduced by a short change and you make a loss on the trade (buy at BUY1 and sell at SELL3).

**Feature Suggestion**
This could be circumvented with an additional function by activating only those sales whose purchases were previously fulfilled, as shown in Figure 2. This way you would always reach the previously set spread.

**Additional context**

Picture1:
![Hummingbot1](https://user-images.githubusercontent.com/23531655/95310203-69e52280-088c-11eb-9bf1-e7c0e8fee1ff.jpg)
Picture2:
![Hummingbot2](https://user-images.githubusercontent.com/23531655/95310230-723d5d80-088c-11eb-8570-e11f1a024f1d.jpg)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakge2) by [Unito](https://www.unito.io)

**Comment by ChristianFeldmannHamm** [comment]
I have been following my trades over the last few days and have noticed that this kind of behavior occurs again and again. Under certain circumstances, this can lead to a loss due to the fees, although the previously designed spread should yield a profit.

![Kurs1_1](https://user-images.githubusercontent.com/23531655/96177932-f055d000-0f2e-11eb-8c08-4319833f3edf.jpg)

**Comment by mifeng** [comment]
@ChristianFeldmannHamm The fix proposed in Picture2 seems to change the nature of hanging orders, which are designed to keep an order around if the other side was filled, so that it gets hit again if the trend reverses. In fact, I would argue that 
in the Picture1 chart, a trader would want hanging orders as currently designed so that they are each triggered as the price recovers. In other words, BUY1 should be compared vs SELL1, not SELL3.
