### ISSUE TITLE
[Feature] Redesign how kill switch feature works

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#2497]
**Feature Suggestion**
When Issue #2383 is implemented, it could be used to change the behavior of the `kill_switch_enabled` setting.

Instead of completely stopping the bot when `kill_switch_rate` is reached, the bot could `pause` instead. (Or add an option between stoping and pausing)

**Impact**
Since `Return %` is based on the total inventory value and affected by the current price, sudden and quick price movements (aka pump and dumps or flash crash) may force the bot to stop through `kill_switch_enabled`, but the price could return to the normal trading levels, and the `Return %` to the value it was before the move.

In this case, with the bot stopped, the market maker activity wouldn't be resumed as normal and would need the user to restart it, resulting in an opportunity loss.

If `kill_switch_enable` pause the bot, instead of stopping it, the mm activity would be resumed if the inventory value returned to acceptable levels (defined by the user).

This would allow for a more automated safety measure.

**Additional context**
![image](https://user-images.githubusercontent.com/34484531/96638521-a2f2ad80-12f6-11eb-9a2d-bc777bf2fc38.png)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakht0) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
This is a good idea - we should make `kill_switch` more flexible in
- what drives it? rate of return, inventory base %, market volatility, etc
- what happens when bot is stopped? all orders cancelled / only active orders cancelled
- when drives resumption of activity?

Trying to parametrize all these options would be complicated and create an expensive maintenance and testing burden in the future, so I think rather than building upon the existing `kill_switch` feature, we should convert it into an editable script instead.

So I think the scope of work for this story should be to build a Kill Switch script that supports the options above. This should be possible after #2383

**Comment by phbrgnomo** [comment]
@vic-en Since now we can set order_levels to 0 on the fly, could we use it to change the behaviour for the kill_switch?

**Comment by dennisocana** [comment]
This enhancement is one of the most requested by the community in Discord conversations. Will take a look at this and discuss for implementation near-term.
