### ISSUE TITLE
Respect current bid-ask spread when using external price source

### ISSUE THREAD

**Issue by ZeroCool940711** [hummingbot/hummingbot#2536]
**Describe the bug**
When using the Pure Market Maker strategy Hummingbot buys high and sell lower than where it bought most of the time. When using hanging orders they work perfectly but non-hanging orders (normal maker limit orders) are the problem, on a stable market or also when it's moving uptrend this behavior is not a problem but when the market is downtrend or volatile this problem causes massive losses, 99% of my losses are because of this behavior.

**Steps To Reproduce**
In order to reproduce this behavior a few key things need to happen:
1- You are using hanging orders with a high `hanging_orders_cancel_pct` value so the hanging orders are not cancelled when the market moves or you started with a small inventory.
2- Most of your inventory needs to be in use by your hanging orders and only a small portion on one side is available to trade, that portion needs to be enough for Hummingbot to place one order on that side or if you started with a small inventory you only have enough on one side for a single order.
3- Market needs to be downtrend or volatile so the next order is not placed exactly at the same price the previous one was placed and there is a different on the mid price big enough so when the `bid_spread` and `ask_spread` trigger it will place the orders far from the previous filled order on the other side.

**Screenshots**
Example of Hummingbot placing multiple orders and losing money on most of them due to this behavior.
![image](https://user-images.githubusercontent.com/5977640/97676115-5bce9000-1a4d-11eb-9965-e29f3c0dba31.png)

What I expect Hummingbot to do in these cases is sell only above the previous order filed on the other side, this also applies the other way, if a sell order was filled on one side it should only buy below that price and not above it, this behavior is similar to what the `order_type: last_own_trade_price` does but the problem with using that option is that it can not be used with `mid_price` as `order_type` because they are both part of the same config and only one of them can be used at the time, to explain it a bit better, when using `last_own_trade_price` it uses that order as reference point to place the next order instead of `mid_price`, this should fix the behavior I mentioned before but the problem comes when the market moves, if your last filled order was for example a buy order for BNB-USDT placed at 28.00 USDT and the market moves uptrend and is now at 30.50 USDT HB will not place any sell order there as it's too far from the previous order filled even if this order would be a profitable trade. If using `mid_price` as reference there would be a sell order at 30.60 USDT for example and that would fill the previous order in a way that it will fit both options.

My solution is to implement either `last_own_trade_price` as a different option where it can be used alongside `mid_price` or implement a new option to handle this, I have a few ways this can be done, a simple way to do this would be an option called `last_trade_profit_enabled=true/false`, when this option is set to `true` HB will only place an order on the other side if that order will give any profit against the last placed order on the other side. Another way to implement this is to add a way to track what orders have been filled with a matching order on the other side, treating all orders as pairs, similar to hanging orders but without the need to place two orders on each side at the same time, they could be placed one first on a side, mark it as not_filled and then place an order on the other side later to fill this specific order.

**Release version**
Version: dev-0.33.0

**Attachments**

Config and log file for the strategy in case of been needed:
[conf_pure_mm_binance_us_bnb_usdt_1.zip](https://github.com/CoinAlpha/hummingbot/files/5464098/conf_pure_mm_binance_us_bnb_usdt_1.zip)
[logs_conf_pure_mm_binance_us_bnb_usdt_1.zip](https://github.com/CoinAlpha/hummingbot/files/5464106/logs_conf_pure_mm_binance_us_bnb_usdt_1.zip)

Global config and script I'm currently using, the script is just to adjust the spreads a bit when the market is volatile.
[conf_global.zip](https://github.com/CoinAlpha/hummingbot/files/5464112/conf_global.zip)
[spreads_adjusted_on_volatility_script.zip](https://github.com/CoinAlpha/hummingbot/files/5464114/spreads_adjusted_on_volatility_script.zip)

**Optional:**

Discord Username:  Tukirito#1748

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakr1g) by [Unito](https://www.unito.io)

**Comment by ChristianFeldmannHamm** [comment]
Hello, I think I have experienced a similar or even the same condition. Is my suggestion not the same as yours?

https://github.com/CoinAlpha/hummingbot/issues/2451

**Comment by ZeroCool940711** [comment]
@ChristianFeldmannHamm I think they are both related, you did a good job explaining it better than me on your issue, I think we should keep both issues open, yours as a feature requests and mine as a bug report as it's valid for both cases as I think it shouldn't be happening in the first place (bug) and also needs some improvements so it's also a feature request.

**Comment by TradeClaw** [comment]
Isn't this just what pure market making is during a down trend?

Sounds to me like you are rather asking for a DCA price source implementation?
You would basicly need unlimited funds (same as the crazy amount of hanging orders today possible) or the bot goes inactive until price recovers, which can take a year or more in some cases coz your average price doesn't go down as much anymore after a few buy order hits. (check martingale)

You can develop your own strategies from what I understand, think that's more what you need as a solution.

I might not fully understand what you are reporting, also a possibility 👍

**Comment by mifeng** [comment]
I clarified with the user about this issue. Currently, Hummingbot treats different price sources as the new mid price and creates a two-sided market around it. However, in cases when the current best bid and ask are far away from the price source, buy or sell orders may not be created when they should.

For example, let's say a sell order was filled at price 100. Afterwards, the price moves down to 90. In order to realize a profit on your earlier trade, you would be happy to buy at the current price. Currently however, the bot using `last_own_trade_price` would try to set 2-sided orders around 100. Only the sell order > 100 gets placed, while the buy order doesn't get placed even though it would realize a profit. Instead, this scenario should result in the buy order placed at best bid.

This requires 2 preliminary changes:
- Move price quantization out of the `c_create_base_proposal` and into a separate function that is performed for all orders prior to submitting order proposals.
- Record both the price and the side (buy or sell) for `last_own_trade` and `last_trade`, so that side can be incorporated into market making decision using those price sources

When `price_source` is `last_own_trade` or `last_trade`:
1. If last trade was SELL and current `best_bid` < trade price, place buy order equal to `best_bid` + 1 tick.
2. Similarly, if last trade was BUY and current `best_ask` > trade price, place sell order equal to `best_bid` - 1 tick.

This is what order optimization does already, so we should ideally use that function to make the adjustments.

**Comment by ZeroCool940711** [comment]
@mifeng Any news about when or if this is going to be implemented? 
I though this would be on version 0.34.0, do you think this could be part of the next version or is it going to take longer?

**Comment by phbrgnomo** [comment]
@ZeroCool940711 A few version after this issue was opened we implemented a new `price_type` name `inventory_cost`.

Have you tested it? I see that the main issue would be to make the bot avoid creating selling orders on an unprofitable position.

Can you confirm if this new feature would solve your problem?

**Comment by ZeroCool940711** [comment]
@phbrgnomo I tried using it but didn't understand how exactly it works so, most likely I was using it the wrong way, it would be nice if you could give me some information on how it works and how to use it, also I think more information about the different `price_type` should be added to the documentation so its easier to search for it.
