### ISSUE TITLE
[Feature] Allow order_amount to be quote based

### ISSUE THREAD

**Issue by TradeClaw** [hummingbot/hummingbot#2579]
**Feature Suggestion**
Right now, order_amount is asset based.
Allowing quote based order_amount after entering 0 on the asset based question.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to create equal quote size orders.
Right now if you work with the minimum order sizes, when price drops a bit then orders do not comply with the exchange required size.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakruf) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
Tangentially, if orders are failing due to minimum size restrictions, some output in the UI or logs would be useful. I had a bot 'hang' for apparently so reason, was simply not placing orders, but otherwise was functioning and responding ok. After some help from QA it turned out to be a minimum order problem.
