### ISSUE TITLE
Coinbase Pro - Failing to cancel hanging orders

### ISSUE THREAD

**Issue by cryptohustlin** [hummingbot/hummingbot#3074]
**Describe the bug**
// A clear and concise description of what the bug is.

hanging orders seem to be un-cancelable via hummingbot when making hundreds of orders intermittently which leads to the bot failing to place orders / cancel orders.

![image](https://user-images.githubusercontent.com/29321148/111043217-350a6800-83f6-11eb-9cf0-ac99f795d196.png)
![image](https://user-images.githubusercontent.com/29321148/111043220-39368580-83f6-11eb-87d5-acd3df71207f.png)

the bot seems to often think it has a bunch of orders that don't actually exist. 

![image](https://user-images.githubusercontent.com/29321148/111043251-684cf700-83f6-11eb-89a4-076137d73bdb.png)
![image](https://user-images.githubusercontent.com/29321148/111043253-6b47e780-83f6-11eb-8130-385f9320b42d.png)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: ...

I have been using custom ladder + hanging orders + inventory skew

1. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

0.37.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[conf_pure_mm_1.zip](https://github.com/CoinAlpha/hummingbot/files/6135479/conf_pure_mm_1.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**
cryptohustlin#1450

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram96a) by [Unito](https://www.unito.io)

**Comment by AngeredZeus** [comment]
This may have to do with the exchange's api_request function
https://github.com/CoinAlpha/hummingbot/blob/8ac56466b606f7780d448ab14b24cd0f9e40d94a/hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx#L298
It needs to include throttling in order to handle canceling / updating so many hanging orders.

**Comment by cryptohustlin** [comment]
![image](https://user-images.githubusercontent.com/29321148/111081779-da3a4480-84b9-11eb-87d9-c7cb91b68de6.png)
seems like i run into 429's trying to cancel orders fairly often.

**Comment by stekam69** [comment]
pure_market_making  config when issue happend settings during the issue
hanging_orders_enabled: True
max_order_age: 1800.0
order_refresh_time : 900  (not sure but was more than 20min)
Filled_order_delay 1800
order_levels: 1


I have also on coinbase same issue since 2 days , and now I have two hunging orders

            Level    Type    Price       Spread        Amount (Orig)  Amount (Adj)       Age
             hang  buy      0.007789  4.30%                        0.15                              21:33:13        

repeated screen output
10:20:07 - pure_market_making - Refreshing Buy order with ID - buy-COMP-BTC-16177921XXXX5530 because it reached maximum order age of 1800.0 seconds.

shutting down says:

10:20:18 - coinbase_pro_exchange - Failed to cancel the order buy-COMP-BTC-1618042XXXXX2722 on Coinbase Pro. 
                 Check API key and network connection.
10:20:18 - coinbase_pro_exchange - Failed to cancel the order buy-COMP-BTC-16177921XXXX5530 on Coinbase Pro. 
                 Check API key and network connection.

all other bots are working fine

**Comment by MementoRC** [comment]
@rapcmia @cardosofede This needs to be closed, Coinbase Pro no longer exists, it has been replaced by Coinbase Advanced Trading almost completely new API

**Comment by stekam69** [comment]
yes please close it,
thanks,
