### ISSUE TITLE
Pure MM - Problem when configuring `price_type` to `inventory_cost`

### ISSUE THREAD

**Issue by smalltimepro** [hummingbot/hummingbot#3302]
**Describe the bug**
Trying to start a bot which has price_type configured as inventory_cost is refusing to start. Both for new and for bot that has previously been running on the same config but has just been restarted. 
The system complains about missing configuration on strategy 'inventory_price'. For a bot that is being restarted I am able to manually input a price by reconfiguring 'price_type'. This should not be the case as system already has history
For a new bot with zero inventory the element is unconfigurable. If the account has no base asset, why ask for a inventory_price, nothing has been bought yet.

**Steps To Reproduce**
Start/import a bot Config price type -> inventory_cost

..

**Screenshots**
![image](https://user-images.githubusercontent.com/26482052/116525576-90be8100-a8d0-11eb-8f99-8b91a0de12a6.png)
![image](https://user-images.githubusercontent.com/26482052/116527591-bfd5f200-a8d2-11eb-8acc-df3e62266ece.png)

**Release version**
0.38.1

**Attachments**

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramcny) by [Unito](https://www.unito.io)

**Comment by R-K-H** [comment]
Check your `order_amount` config value, it's like because the price changed of the asset and therefore you no longer meet the exchange's min requirement. Type `config` and then my guess is you'll see `None` for that value.

**Comment by smalltimepro** [comment]
No this not correct. There is nothing wrong with my order_amount or any other config. There are two cases in this issue.
1. Newly config with zero inventory on base asset. Does not allow to set inventory_price through manual entry. This may be due to some divide by zero issue/bug. Same bot config will start with mid_price confirming nothing wrong with other params
2. Restart bot that has already been running on price_type inventory_cost. Forces manual re-entry of inventory_price. In this case bot will accept manual entry but it should not ask as the inventory price should be saved accross sessions

**Comment by rapcmia** [comment]
Hi, @smalltimepro I tried to create a default config for HNT-USDT with 0 base assets. When I set the `price_type` to inventory_cost, I got the same error however when I checked the `config` the price_type has been changed to inventory_cost. Since it's already changed, I ran `config inventory_price` as well getting the same behavior and error attached. Restarted the bot changed back to mid-price, the bot seems to be creating orders. Changed back to price_type = inventory cost getting the same behavior again. 
 
 
![image](https://user-images.githubusercontent.com/73840223/116778700-15162d00-aaa6-11eb-9e71-836b16321455.png)

 
 Just checking if you can share the logs of the bot you use to get the error? 
 
 Release verison: 
 version dev-0.39.0
 
 Attached files:
 
[logs_pmm-3302.log](https://github.com/CoinAlpha/hummingbot/files/6409338/logs_pmm-3302.log)

**Comment by smalltimepro** [comment]
i was using it on live. i did not try paper. The key issue was always when trying to set inventory_price. The behaviour occurs only if there is no base_asset in the inventory, so I am assuming the bug is in code that gets confused on what value to assign. I would suggest that there should be a check to see if there is no base asset and therefore no need to assign an initial 'inventory_price'
I do not have any logs because the bot never started, it would hang every time I tried to assign the price in config

**Comment by rxlxrxsx** [comment]
Hi @smalltimepro, I can't seem to replicate the behavior you reported. I tried setting the `price_type` to `inventory_cost` with 0 base asset, 0 quote asset and 0 base and quote asset but the behavior didn't show at all.

<img width="700" alt="Screen Shot 2021-05-04 at 9 29 38 AM" src="https://user-images.githubusercontent.com/64377055/116951787-60edef80-acbb-11eb-8556-f7026c0a9be9.png">

As for the missing `inventory_price` value during importing, the current design is to manually enter the `inventory_price` when importing a strategy. Reason being as the prices may change during those period.

**Comment by smalltimepro** [comment]
Hi @rxlxrxsx, it is strange because I tried on a new pair just now and didn't get the behaviour either. It is possible some other element combination triggers this, because I tried to make it work doing several restarts and at least one other user (@rapcmia ) managed to replicate it.
Regardless I would suggest asking for inventory price of 0 items is redundant and should not be done anyway.

For `inventory_price` after `import`, I see the reason for prices might have changed, but in that case the user can always manually change, the default behaviour can be restoring last calculated price.

**Comment by Mayhem-Tv** [comment]
i understand this problem....all is needed to make inventory_price operate correctly is to have inventory price = order fill price. simple in theory. how to implelment in code.....I dont know

**Comment by Spike-77** [comment]
I have run balance and verified that I have both sides of the trade.  I am running hummingbot in a live trading session on binance US.

The inventory price and price_type = inventory_cost does not seemed to be resolved in 1.8.0 version of hummingbot.  If you place the inventory_price on the same line as during a config the inventory_price can be set otherwise you will be bounce back to the standard prompt and inventory_price will not be set.

![Inventory_price](https://user-images.githubusercontent.com/104741848/196045875-a1298b66-ed15-4874-9272-2c553ed48e4d.png)

Place the price inline allows the price to be set, but does not fix the price_type=inventory_cost.  In fact this leads to an API limit error.

After inventory_price set inline **avoiding** prompts.

![After_Inventory_cost](https://user-images.githubusercontent.com/104741848/196046049-cf0c4881-29b1-4b7b-934e-0bd7393559ba.png)

If you try and set the price_type = inventory_cost now you will get an API limit error and hummingbot will be stuck in a loop not resolving the price_type and only allowing the user to exit out of hummingbot.

![Setting_inventory_cost](https://user-images.githubusercontent.com/104741848/196046172-c57093a4-f606-465c-9b30-ecb2bdb236de.png)

**Comment by Spike-77** [comment]
If you try and change inventory_price you will not get prompts afterward and get sent right back to the initial prompt.

![Inventory_price_problem](https://user-images.githubusercontent.com/104741848/196046838-f517501a-9f42-4b74-88f9-ddbf731a2a06.png)

The only way to set inventory_price is to set it inline.
config inventory_price "Your Price"

![Inventory_price](https://user-images.githubusercontent.com/104741848/196046860-b2945e26-8243-4e4f-b305-b190f515511b.png)

This starts your problem with changing price_type = inventory_cost

**Comment by mss7082** [comment]
I have the same  isssue. However instead of the api limit. I get this error on FTX. Even though inventory_cost in set.

"RuntimeError: Initial inventory price is not set while inventory_cost feature is active.
2022-10-16 14:45:51,905 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick."

![image](https://user-images.githubusercontent.com/6820077/196049556-80f4790e-6e67-40b7-89e3-752ee7d5e1af.png)

**Comment by mss7082** [comment]
Wierd, started a new pmm strategy and set inventory_price to 0. and that seems to make it work. Strange.

![image](https://user-images.githubusercontent.com/6820077/196051716-5245f49d-111e-4e0b-8ac8-e6f0c94bc35a.png)

![image](https://user-images.githubusercontent.com/6820077/196051730-a5137b01-6936-42cd-ad66-d6724f125111.png)

**Comment by Spike-77** [comment]
The above solution did not work on Binance US.  There is an issue with setting the inventory_price for BTC/USD pair and maybe other pairs on Binance US.

**Comment by mss7082** [comment]
Yea, did not work for btc/usd on ftx as well.

Another workaround that i tried that seems to work for me, anyone interested can try to confirm.

1. Create your strategy. set the price_type and inventory_price inline.
2. Exit the bot
3. Add the cost to the InventoryCost table in the sqlite file (found in the hummingbot_data folder) manually. (It wouldn't let me update the db in place, so i uploaded the file to https://sqliteonline.com/ inserted the required fields - `INSERT INTO InventoryCost (id,base_asset,quote_asset,base_volume,quote_volume) VALUES (1,'BTC','USD',0.01440,273.6);`)
4. saved the sqlite file locally, and copied back to the hummingbot_data
5. Start the bot
6. import the strategy file
7. set the inventory_price inline
8.  start.
