### ISSUE TITLE
Rate oracle - unable to get the rate of wrapped tokens

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#3555]
**Describe the bug**
When trying to get the rate of wrapped tokens for example WETH, WCELO, WCUSD, etc. we get a result of `Rate is not available` despite using Coingecko as the rate_oracle_source. Only WBTC token has a rate base on the test done.
With this behavior, this prevents the amm_arbitrage strategy to fail to start if you use any of those wrapped token that doesn't have rate conversion.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Start Hummingbot and change the `rate_oracle_source` to `Coingecko`
1. Run `rate --token [wrapped token]` or `rate --pair [wrapped market]`
1. Setup gateway and create an AMM arbitrage strategy and use any wrapped market except WBTC then start the strategy.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/121443803-c8851200-c9c0-11eb-9584-83547aa44619.png)
v.0.40.0
![image](https://user-images.githubusercontent.com/57189990/121444170-8b6d4f80-c9c1-11eb-8225-edca0d1527c0.png)

**Release version**
0.39.0
**Attachments**

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramq1x) by [Unito](https://www.unito.io)

**Comment by EmmeCorelli** [comment]
**I'm new.**
I'd like to participate to the project, so I start to take a look to this issue.

The issue is not a bug but a limitation due to ask the price, see:

RateOracle.get_prices that call RateOracle.get_coingecko_prices, the first lines of comment are:

        Fetches CoinGecko prices for the top 1000 token (order by market cap), each API query returns 250 results,
        hence it queries 4 times concurrently.

The solution is change the function to iterate over 4 pages but this cost time to retrive the infos. I suggest to add a configuration flag to set to iterate to all the token.

Please give me a feedback

m.c.
