### ISSUE TITLE
Kraken Tests failing due to non existent asset

### ISSUE THREAD

**Issue by TheHolyRoger** [hummingbot/hummingbot#4311]
**Describe the bug**
Kraken tests are failing due to non-existent asset, not sure if this is intentional?

I'll be honest I don't really understand the new test suite syntax/workflow petioptrv is there any documentation you could point me at please?

For example have the old environment variables for api keys been removed?

```
-------------------- >> begin captured logging << --------------------
hummingbot.core.utils.async_utils: ERROR: Unhandled error in background task: Error fetching Kraken market snapshot for COINALPHA-HBOT. Error is ['EQuery:Unknown asset pair'].
Traceback (most recent call last):
  File "/home/runner/work/hummingbot/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/runner/work/hummingbot/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 178, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/runner/work/hummingbot/hummingbot/hummingbot/connector/exchange/kraken/kraken_api_order_book_data_source.py", line 117, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_snapshot(
  File "/home/runner/work/hummingbot/hummingbot/hummingbot/connector/exchange/kraken/kraken_api_order_book_data_source.py", line 103, in get_snapshot
    raise IOError(f"Error fetching Kraken market snapshot for {original_trading_pair}. "
OSError: Error fetching Kraken market snapshot for COINALPHA-HBOT. Error is ['EQuery:Unknown asset pair'].
```

**Steps To Reproduce**
Run Kraken tests

**Release version**
development

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran7mk) by [Unito](https://www.unito.io)

**Comment by petioptrv** [comment]
@TheHolyRoger, can you point me to the tests you're running please? They all pass on my end (see attached screenshot).

One thing to note is that there are currently two sets of tests for the Kraken connector. The first one chronologically is under `test/connector/exchange/kraken`. These are integration tests really, since they interact with the actual Kraken server. The more recent set of tests is under `test/hummingbot/connector/exchange/kraken`. Those are unit tests where the API responses for both REST endpoints and websocket connections are mocked.

The first set of tests is bound to give you some problems as those are not ran by the GitHub CD pipeline and may be out outdated. 

As for how the mocking is performed, we don't have a specific documentation yet, but we use [`aioresponses`](https://github.com/pnuckowski/aioresponses) to mock REST API requests made with `aiohttp`, and a combination of [`patch`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) and our [`NetworkMockingAssistant`](https://github.com/CoinAlpha/hummingbot/blob/development/test/hummingbot/connector/network_mocking_assistant.py) to mock websocket connections made using either `aiohttp` or `websockets` (which is the case of Kraken).

You can see examples of both in the [user stream data source unit tests for Kraken](https://github.com/CoinAlpha/hummingbot/blob/development/test/hummingbot/connector/exchange/kraken/test_kraken_api_user_stream_data_source.py).

<img width="1087" alt="Screen Shot 2021-09-29 at 10 36 01 AM" src="https://user-images.githubusercontent.com/15842646/135198917-b401dc31-4ffd-428d-a33b-dc12f2691a28.png">

**Comment by rapcmia** [comment]
Tagging this issue as resolved, no reported Kraken test failing on recent Github validation checks
