### ISSUE TITLE
Impossible to get complete RateOracle coverage

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#4439]
**Describe the bug**
If you have accounts on both AscendEx and KuCoin, featuring variety of tokens used in liquidity mining, there's no setting for RateOracle that will give you complete price coverage, so eg. balance command will not work as expected

The most complete price source would be coin gecko, but some of the tokens - for me, at the time of writing, NIOX on AscendEx and NDAU on KuCoin - are not returned in the API, despite being available on the website

One possible solution would be to have a RateOracle setting that merges price dictionaries from multiple sources

**Steps To Reproduce**
Have a balance of NIOX on AscendEx and NDAU on KuCoin

Run 'balance' command with different rate_oracle_source configs (coingecko, ascend_ex, kucoin)

Note that in all settings at least one of NIOX and NDAU total will be zero

**Optional: your discord username:**
zappra

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0fb1) by [Unito](https://www.unito.io)

**Comment by globeone** [comment]
**Describe the bug**
// A clear and concise description of what the bug is.

While liquidity mining on KuCoin, Ascendex or Gate.io when one enters the *status* command there is a filed Miner Rewards/wk. This is set to 0 for trading pairs, even though the dashboard shows rewards.
Note: the behavior doesn't happen with Binance

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Configure Liquidity Mining on Hummingbot and set several trading pairs.

In the example in the screenshot KuCoin all the BTC markets.
As one can see in the screenshot the SHR-BTC pair shows 0 under the Rewards/wk column of Miner.
The dashboard shows that there is USDT 273 available in rewards

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

see config file

**Screenshots**
// If applicable, add screenshots to help explain your problem.

h3. KuCoin
![image](https://user-images.githubusercontent.com/10052587/146619425-b9b150f8-fe59-4bf4-9646-a22a1e15a1a8.png)

h3. Ascendex
![image](https://user-images.githubusercontent.com/10052587/146619669-204d114d-b334-4000-8d4f-354a22f24a97.png)

![image](https://user-images.githubusercontent.com/10052587/146620504-ec150e46-7b81-4fa6-b497-88e29773e0a7.png)


h3. Gate.io
![image](https://user-images.githubusercontent.com/10052587/146619692-f96b6696-ae99-4371-8ca5-7bede7da77ca.png)

![image](https://user-images.githubusercontent.com/10052587/146620599-309e28af-7d09-4c54-a294-cb41b520141f.png)


h3. Binance (doesn't have the issue)
![image](https://user-images.githubusercontent.com/10052587/146619726-e1e8a141-98af-424b-baaf-862bc7ab5786.png)


**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

h3. KuCoin BTC
[conf_liquid_ku_btc.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738305/conf_liquid_ku_btc.yml.txt)
[hummingbot_logs.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738308/hummingbot_logs.yml.txt)

h3. Ascendex USDT
[conf_liquid_ascendall.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738309/conf_liquid_ascendall.yml.txt)

[ascendex_hummingbot_logs.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738311/ascendex_hummingbot_logs.yml.txt)

h3. GateIO 

[conf_liquid_gate_usdt.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738317/conf_liquid_gate_usdt.yml.txt)
[gateio_hummingbot_logs.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7738319/gateio_hummingbot_logs.yml.txt)




*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Bhagavate bilala#6332
