### ISSUE TITLE
Perpetual MM - Remove trailing stop position management option

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#4501]
## Why
Currently, the strategy has two position management methods configurable through `position_management` param:

1. `Profit_taking`
1. `Trailing_stop`

The objective is to simplify the strategy for now while trailing stop is too complex to understand and use effectively. Eventually, adding trailing stop again can be revisited on the future after a proper redesign.

## What
* Remove `position_management` parameter
* The strategy's position management method should always be `Profit_taking`
* Remove params `ts_activation_spread` and `ts_callback_rate` since these are only used with trailing stop

## Definition of Done
* [ ] The `position_management` parameter is removed along with `Trailing_stop` feature
* [ ] Perpetual MM to always perform `Profit_taking` behavior
* [ ] Params `ts_activation_spread` and `ts_callback_rate` are removed from config map as well their usage in the codebase

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cxe) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
I agree that since we plan to remove `Trailing_stop`, the default position management method should be `Profit_taking`. Some additional comments:

1. Because it will be the only position management method, we should also remove `position_management` paramater
2. Remove `ts_activation_spread` and `ts_callback_rate` since these are only used with trailing stop
