### ISSUE TITLE
hummingbot-development avellaneda severely broken 

### ISSUE THREAD

**Issue by dkreeg** [hummingbot/hummingbot#4852]
![ave_screen](https://user-images.githubusercontent.com/95381505/144444686-f74717da-8068-41ab-84a0-e8d25fd5ab73.png)

**Comment by RC-13** [comment]
Hello @dkreeg can you please update your development branch and try again? First, go inside the Hummingbot directory that you downloaded then do the following steps:
```
./clean
conda deactivate
./uninstall
git fetch origin
git pull origin development
./install
conda activate hummingbot
./compile
```
I tried testing the avellaneda market making strategy using a different market since I don't have sufficient asset for the market that you are using and the bot was able to open an order.
Risk factor =1 
![image](https://user-images.githubusercontent.com/57189990/144791631-0c057c4b-5086-44fe-86cf-e02bf3b92905.png)

Using a high risk factor:
![image](https://user-images.githubusercontent.com/57189990/144788059-36f97534-d726-4cfb-bc03-2b2c5fdb21ab.png)

**Comment by dkreeg** [comment]
Still getting unacceptable values. Wondering if it has to do with the volatility generated in illiquid pairs, or order books with low trade frequency. 
![Screenshot from 2021-12-06 09-45-37](https://user-images.githubusercontent.com/95381505/144881534-0fa11a60-98f3-4111-b772-e6cc9fb99e72.png)

**Comment by mhrvth** [comment]
Yes, the risk_factor and other parameters are completely different now. Please see the updated documentation. 
I'm closing this as it's a settings issue. Feel free to reopen it if you're still getting wrong prices.

**Comment by rapcmia** [comment]
Hi @dkreeg, there are improvements added to our Avellaneda strategy with the recent release [Hummingbot 1.0.0](https://hummingbot.org/release-notes/1.0.0/#improved-avellaneda-market-making-part-2). We suggest to look into it again and visit our [discord ](https://discord.com/invite/hummingbot)if support is needed. We will be tagging this ticket as closed for now, thank you
