### ISSUE TITLE
Binance - Continuously creating orders that are below exchange's minimum order size

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5091]
**Describe the bug**
While testing the Binance connector, if the set `order_amount` is below the exchange's minimum order it will still try to create an order with returning an error of `..order amount 0 is lower than minimum order size 1.0000..` and repeat on every order cycle

![image](https://user-images.githubusercontent.com/73840223/152494272-c5a68581-ba2e-4b0d-8378-cc24a5708542.png)

**Steps To Reproduce**
1. Setup market-making strategy (Tested on Pure market making)
2. Set your order amount below [Binance's minimum order size](https://www.binance.com/en/trade-rule) (Tested XRP-USDT)
3. Set order_refresh_time to 5s, then start the bot 

**Release version**
version 1.0.0

**Attachments**
[pmm-test.zip](https://github.com/hummingbot/hummingbot/files/8001165/pmm-test.zip)

**Comment by sisco0** [comment]
By running the next command under the terminal, the _API_ shows relevant information under its `exchangeInfo` endpoint:
```bash
curl https://api.binance.com/api/v3/exchangeInfo\?symbol\=XRPUSDT | jq --color-output
```
The relevant information for us is shown in the `MIN_NOTIONAL` filter, where the minimum order size for the destination unit is shown.

It should be discussed if a solution for _Binance_ could consist of checking this restriction at the start of the strategy, and disabling the strategy when the issue scenario occurs; take into account that this is a solution that would apply only for _Binance_.
Is the proposed one a feasible solution?

**Comment by leastchaos** [comment]
```
    def quantize_order_amount(self, trading_pair: str, amount: Decimal, price: Decimal = s_decimal_0) -> Decimal:
        """
        Applies the trading rules to calculate the correct order amount for the market
        :param trading_pair: the token pair for which the order will be created
        :param amount: the intended amount for the order
        :param price: the intended price for the order
        :return: the quantized order amount after applying the trading rules
        """
        trading_rule = self._trading_rules[trading_pair]
        quantized_amount: Decimal = super().quantize_order_amount(trading_pair, amount)

        # Check against min_order_size and min_notional_size. If not passing either check, return 0.
        if quantized_amount < trading_rule.min_order_size:
            return s_decimal_0

        if price == s_decimal_0:
            current_price: Decimal = self.get_price(trading_pair, False)
            notional_size = current_price * quantized_amount
        else:
            notional_size = price * quantized_amount

        # Add 1% as a safety factor in case the prices changed while making the order.
        if notional_size < trading_rule.min_notional_size * Decimal("1.01"):
            return s_decimal_0

        return quantized_amount
```
```
        self.start_tracking_order(
            order_id=order_id,
            exchange_order_id=None,
            trading_pair=trading_pair,
            trade_type=trade_type,
            price=price,
            amount=amount,
            order_type=order_type)

        if amount < trading_rule.min_order_size:
            self.logger().warning(f"{trade_type.name.title()} order amount {amount} is lower than the minimum order"
                                  f" size {trading_rule.min_order_size}. The order will not be created.")
            order_update: OrderUpdate = OrderUpdate(
                client_order_id=order_id,
                trading_pair=trading_pair,
                update_timestamp=int(self.current_timestamp * 1e3),
                new_state=OrderState.FAILED,
            )
            self._order_tracker.process_order_update(order_update)
            return
```
I think the order is not sent to the exchange. the notional part is already checked by the quantize_order_amount although it is using current price instead of the placed price but increasing the min notional to *1.05 should be reasonable enough for most users already if needed as it is quite a small difference. $10.1 vs $10.5
As it is below notional value, the quantum order size returns 0. The code is just posting a order fail event as it has started tracking. 
Other exchanges check for this first before starting the order tracking though and only a raise value error is performed instead of warning + orderfail event. so probably follow same way as other exchanges?

from ascendex
```
        if amount <= s_decimal_0:
            raise ValueError("Order amount must be greater than zero.")
        try:
            timestamp = ascend_ex_utils.get_ms_timestamp()
            # Order UUID is strictly used to enable AscendEx to construct a unique(still questionable) exchange_order_id
            order_uuid = f"{ascend_ex_utils.HBOT_BROKER_ID}-{ascend_ex_utils.uuid32()}"[:32]
            api_params = {
                "id": order_uuid,
                "time": timestamp,
                "symbol": ascend_ex_utils.convert_to_exchange_trading_pair(trading_pair),
                "orderPrice": f"{price:f}",
                "orderQty": f"{amount:f}",
                "orderType": "limit",
                "side": "buy" if trade_type == TradeType.BUY else "sell",
                "respInst": "ACCEPT",
            }
            self.start_tracking_order(
                order_id=order_id,
                trading_pair=trading_pair,
                trade_type=trade_type,
                price=price,
                amount=amount,
                order_type=order_type,
            )

```

**Comment by dennisocana** [comment]
I don't think it's a bug. The expected behavior is when your order size is below the exchange's minimum for whatever reason, it will not create the order hence, the logging message. The issue I see here is how come you were able to set your `order_amount` below the minimum if we have the validation during prompt?

**Comment by rapcmia** [comment]
Hi @dennisocana I assume this is in line with #4456 there are changes on order_amount, users can set the value even below the connector's min_order_amount

**Comment by dennisocana** [comment]
@rapcmia what's the issue, are orders opened by Hummingbot even if they are below the exchange's minimum?

**Comment by rapcmia** [comment]
Hi @dennisocana Ahh no, no orders are created on the exchange, however I am under the impression that when you `initially start the client` it should not try to create orders and just stop when the set order_amount is below the exchange's minimum requirement. Something like on Ascendex's behevior below if I set the order amount below the minimum
<img width="695" alt="image" src="https://user-images.githubusercontent.com/73840223/159234904-342bf14a-2c04-4a80-8605-1163026c48a4.png">

**Comment by dennisocana** [comment]
@rapcmia we created a PR before to add the logging message you see in Binance as part of UX improvement. This is because users have no idea why orders are not created when the orders they are trying to place are below the minimum, this logging message should help users understand that the `order_amount` should be adjusted. I think it was experimental that's why it's not yet in some other connectors. I will look for the PR or issue for that task.

**Comment by leastchaos** [comment]
just one comment for consideration, maybe this should be added under status warnings instead of the log as it clutters the logs It is very common to meet this criterion in between bot operations e.g the order amount is 1000 units and the min units is 10 if the bot bought 991 units, then the next loop, the buy order of 9 is tried to be created then it will keep printing this message in the logs unnecessary.
