### ISSUE TITLE
Liquidity Mining - Unexpected error while requesting data from Hummingbot API 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5240]
**Describe the bug**
While testing liquidity mining strategy, running `status` command will return an error of `Unexpected error while requesting data from Hummingbot API`. The bot seems to create and cancel order accordingly, no stuck orders on exchange.

![image](https://user-images.githubusercontent.com/73840223/164202181-81f4c159-5c75-4c1f-87e1-3585a0ed8e04.png)

```
2022-04-20 09:53:13,114 - 17099 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
  File "/home/ubuntu/github/staging/hummingbot/connector/parrot.py", line 35, in get_campaign_summary
    campaigns = await get_active_campaigns(exchange, trading_pairs)
  File "/home/ubuntu/github/staging/hummingbot/connector/parrot.py", line 71, in get_active_campaigns
    resp_json = await resp.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://papi.hummingbot.io/v1/mining_data/campaigns')
```

**Steps To Reproduce**
1. Setup simple liquidity mining strategy 
2. Start the bot
3. After creating the orders, run status command 

**Release version**
Version 1.2.0, Staging dev-1.3 and development branch

**Attachments**
[lm-test.zip](https://github.com/hummingbot/hummingbot/files/8520470/lm-test.zip)

**Comment by drlcai** [comment]
Same problem here. I was running the bot in docker with version 1.2 and also from source for the staging version (1.3). Then I  tried status --live command. I got a flashing status report. It seems like it first showed me something then disappeared because of the bug. Then it repeated this error. 

The log file gives: 
2022-04-29 16:40:56,773 - 1 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/parrot.py", line 35, in get_campaign_summary
    campaigns = await get_active_campaigns(exchange, trading_pairs)
  File "/home/hummingbot/hummingbot/connector/parrot.py", line 71, in get_active_campaigns
    resp_json = await resp.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://papi.hummingbot.io/v1/mining_data/campaigns')

**Comment by EkremSel** [comment]
Same problem here

**Comment by DrZuse** [comment]
Same problem. Hummingbot version 1.6, fresh installation with Docker version 20.10.12, build 20.10.12-0ubuntu4

**Comment by DrZuse** [comment]
and looks like it hang whole hummingbot.org server with command `status --live` generating ton of same errors:
![image](https://user-images.githubusercontent.com/53859830/181477194-5309966b-64d1-460d-b997-21989da0146c.png)

**Comment by se-taylor** [comment]
Same issue here. MacOS, using the Docker image install. Release version = v1.6.0

**Comment by MementoRC** [comment]
There is a PR for this:https://github.com/hummingbot/hummingbot/pull/5501

**Comment by JeremyKono** [comment]
Assigning this issue to @MementoRC. Thank you for your contribution!

**Comment by JeremyKono** [comment]
Hi @MementoRC, once again asking for your ETH wallet so that we can make the payment for the bounty. Thanks!

**Comment by MementoRC** [comment]
Jeremy,
My ETH address: 0x8dA825941565a790BDf341B7099FA61296723756
[image: Trust - ETH:0x8dA825941565a790BDf341B7099FA61296723756.png]
Thank you
Claude

**Comment by rapcmia** [comment]
Fix has been deployed
