### ISSUE TITLE
Cython debugger instructions

### ISSUE THREAD

**Issue by charlesdarkwind** [hummingbot/hummingbot#5255]
**Feature Suggestion**
I know this is not related to Hummingbot specifically.
Add instructions on how to set up the Cython debugger `cygdb` with Conda (on Ubuntu)

**Impact**
The desired behavior will allow me to install the Cython debugger to use with hummingbot.
I thought that the hummingbot team possibly already figured this out and are keeping the instructions internally as it looks like [they were previously trying to figure this out themselves](https://gist.github.com/bombs-kim/c9848c2b09962f2fd753b48b6d2cd87f?permalink_comment_id=3312088#gistcomment-3312088).

___

**Additional context**
I was looking at the [Cython debugger doc](https://cython.readthedocs.io/en/latest/src/userguide/debugging.html) and noticed that the procedure to get this working is already fairly complicated with a large number of steps and dependencies.

In addition to the that, those instructions won't allow the use of the debugger with hummingbot out of the box because hummingbot  is using conda.

I tried looking for instructions to set the python debugger using conda which brought me [to this gist](https://gist.github.com/bombs-kim/c9848c2b09962f2fd753b48b6d2cd87f). I see that even @petioptrv was led onto this track but he seems to have made it further than me. 

I personally have trouble figuring how exactly to build hummingbot after configuring `gdb` and following the instructions from the gist:

```
(hummingbot) user@ubuntu:~/hummingbot$ python2-dbg setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from Cython.Build import cythonize
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 48, in <module>
    from ..Compiler.Main import Context, CompilationOptions, default_options
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: /usr/local/lib/python2.7/dist-packages/Cython/Compiler/Scanning.so: undefined symbol: Py_InitModule4_64
```
I did add `cython_kwargs["gdb_debug"] = True` in setup.py

On that note, the vanilla `gbd` does seem to work great by itself with cython and is probably sufficient in most cases from what I have seen.

**Comment by petioptrv** [comment]
@charlesdarkwind those were some investigations I did before joining the team at CoinAlpha. Internally, we do not use the debugger — we use print statements. Another way is to quickly convert a cython module into python (it depends on the module, but this can be very quick). 

Re my investigations, I was able to eventually get it working, but the issue is that the code quickly goes into the compiled C++ code and that's just unworkable, unless you want to parse through all of the checks CPython performs on any operation that remotely touches Python objects. This is the reason we ultimately don't use the debugger for Cython code at CoinAlpha. Debugging Cython works best when the annotated cythonization returns a clean HTML, with minimal Python interactions (see [here](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#primes)).

Btw, those are my notes from that particular investigation (not very complete, as it seems, but maybe they can offer additional help):

- Follow instructions on [website](https://cython.readthedocs.io/en/latest/src/userguide/debugging.html).
	- Make sure `python-dev` package is installed for python2
	- Might have to install `texinfo`
	- If error “error while loading shared libraries: libsource-highlight.so.4”, run `sudo ldconfig`

Good luck!

**Comment by charlesdarkwind** [comment]
@petioptrv Thanks a lot for the notes! Like you say, the heavy use of Python code is going to make things hard.

I was able to use the vanilla `gbd` to spot an exact line causing a segfault. I also previously used it to spot where an infinite loop happened. But both were happening in wrapped c++ code which is not the compiled c++ that Cython produces so it's easily recognizable in the debugger. 

Here are the steps if you ever want to set it up:
```shell
# Install pretty printers
mkdir gdb_printers
cd gdb_printers
svn co svn://gcc.gnu.org/svn/gcc/trunk/libstdc++-v3/python
```
**put this in ~/.gdbinit** :
python
import sys
sys.path.insert(0, '/home/user/gdb_printers/python')
from libstdcxx.v6.printers import register_libstdcxx_printers
register_libstdcxx_printers (None)
end

```shell
# where 25234 is the python process (may need sudo)
~$ gdb -p 25234 -iex "set auto-load safe-path /"

# This should return a bunch of stuff, otherwise it won't be possible to print
(gdb) info pretty-printer 

(gdb) bt
(gdb) up / down
(gdb) info args
(gdb) p arg
```
