### ISSUE TITLE
Rate oracle source - balance returns zero value when using Kucoin and Ascendex as source

### ISSUE THREAD

**Issue by Deepali6997** [hummingbot/hummingbot#5258]
**Describe the bug**

When we run config rate oracle source KuCoin, the balance command starts showing zero value for assets and gross balance for KuCoin exchange.

> MASTER branch

before running config rate_oracle_source in MASTER
<img width="1728" alt="Screenshot 2022-04-25 at 2 14 56 PM" src="https://user-images.githubusercontent.com/100112937/165053633-8483e695-8c7e-40b9-b4b7-0d25c147a157.png">

after running config rate_oracle_source in MASTER
<img width="1728" alt="Screenshot 2022-04-25 at 2 15 29 PM" src="https://user-images.githubusercontent.com/100112937/165053723-8f844900-9b4b-4216-8f1b-c242c2a00128.png">

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Clone the master branch
2. Connect the kucoin exchange with correct API keys credential details
3. Run balance to check the balance
4. Now run command  "Config rate_oracle_source kucoin"

Expected
5. balance should get updated as per rate oracle source : kucoin

Actual
5. the **Total** and **Allocated** values, both stands at zero.

**Release version**
Version 1.2.0

**Comment by RC-13** [comment]
The same issue is seen as well in the development branch
![image](https://user-images.githubusercontent.com/57189990/165092403-fb1ae1e3-9f98-4e30-bd47-2d8748484bbb.png)

**Comment by nikspz** [comment]
Same when using staging branch
![image](https://user-images.githubusercontent.com/83953535/165232681-278d6e46-3bd1-4c58-a8e8-e7473efc44ae.png)

Ascendex also affected: 
`config rate_oracle_source ascend_ex` :
![image](https://user-images.githubusercontent.com/83953535/165232821-a644f0f2-f7d5-430e-8aa3-84cc3da157a4.png)

**Comment by MementoRC** [comment]
This is not an issue. It is due to the fact that for KuCoin (no access to AscendEx) the reference currency is USDT instead of USD, thus if you want to use KuCoin as an oracle, you would need to change your global_token in your global_config.yml (remember to restart to have it effective):
![image](https://user-images.githubusercontent.com/93164135/169704235-f06d8459-9f51-467e-b6ec-dce9d13dad26.png)
![image](https://user-images.githubusercontent.com/93164135/169704278-3886e36d-df6e-4565-a626-2b38572037db.png)
