### ISSUE TITLE
Duplicated orders (after hanging).

### ISSUE THREAD

**Issue by bbbcs** [hummingbot/hummingbot#5390]
**Describe the bug**
Using avellaneda_market_making strategy against kucoin paper trade. When sell order filled, the buy orders keep appending same orders as the first hang (buy) order. See screenshot below.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/5091582/172979587-9d895255-9087-429e-92e8-9094eedd9318.png">

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: avellaneda_market_making using kucoin paper trade, enable hanging order, filled order delay(120) > order refresh time (60)
2. Wait for sell orders filled.

**Screenshots**

<img width="534" alt="image" src="https://user-images.githubusercontent.com/5091582/172979921-0f55f8ad-315e-4c97-847d-39ab14341457.png">

**Release version**
1.4.0

**Comment by bbbcs** [comment]
Update: After the 1st hanging order is canceled (is it a bug?), it looks normal again. 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/5091582/172983972-28f39f15-aace-4298-9cb8-0c8087ff6f65.png">
Now restarting the bot to reproduce...

**Comment by bbbcs** [comment]
Reproduced. Sell side this time. 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/5091582/172986749-70b6b34f-31ec-482d-a72c-9dbfefc8af1a.png">

**Comment by bbbcs** [comment]
Multiple hangs
<img width="687" alt="image" src="https://user-images.githubusercontent.com/5091582/172987271-d147c314-9223-44f8-b425-83a7a8ee3dc4.png">

The duplicated non hanging orders should expire already..

**Comment by nikspz** [comment]
Upon checking the reason of that issue that level_distances is set to 0.
Another value of level distance and orders will be different.
For expired orders it's not cancelled due to order refresh tolerance. 
Here's the results for level_distances 100 and order_refresh_tolerance -1

![image](https://user-images.githubusercontent.com/83953535/174303124-f54e226f-97d4-4e0f-a231-839a39dd7095.png)
![image](https://user-images.githubusercontent.com/83953535/174303167-e0606633-9fab-4782-8c4a-797800640c3a.png)
![image](https://user-images.githubusercontent.com/83953535/174303188-333f393d-33df-4827-b76b-54f472c7db7c.png)
