### ISSUE TITLE
Gate.io - Delay updating Total balance

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5756]
gate.io has delay when updating total balance after the trade happened

**Steps To Reproduce**

1. Create a pureMM strategy using gate.io
2. set up a tight spread to get a trade
3. start the strategy, run `status --live` and wait for a order filled
4. pay attention to total balance

Actual:
There's ~20-30sec delay updating total balance

Expected:
Total balance updating after it changed without delay

**Screenshots**
![5679gate delay](https://user-images.githubusercontent.com/83953535/193192868-90dbffb0-698b-4c65-87cd-00c61a23d967.gif)

**Release version**
dev-1.8.0

**Comment by supervik** [comment]
This issue is related to the changes made in the PR https://github.com/hummingbot/hummingbot/pull/5679
Gate.io websocket balances update now works fine and to fix the total balance issue you only need to revert the commits from the PR above.

I did some tests with the latest 1.11 HB version:
https://www.loom.com/share/1e664f28eaaf402d8fe16bf187b860f6

For the tests I reverted: 3af671f, 6d8ce29, 96c7fda 
and added a line to log websocket event.
On the video is a PMM strategy that places orders and I recorded a filled order to see how it goes.

I also tested withdrawals. Everything was fine, Gate.io sent the balance update without any problems.

**Comment by MementoRC** [comment]
@rapcmia Should this be closed? It is still on the Bounty board

**Comment by nikspz** [comment]
@MementoRC Hmm, not sure why @supervik not assigned to this one yet if he had the solution
@supervik Do you want to be assigned for that bounty?

**Comment by nikspz** [comment]
@supervik Upon checking not sure that reverting remove the ws logic (this commit https://github.com/hummingbot/hummingbot/commit/6d8ce29e12f858a6cd2b624d390464186fa3e94c ) is correct, cause it's the main purpose of https://github.com/hummingbot/hummingbot/pull/5679 PR (5679 is refactor of gate.io connector to the latest standarts)

**Comment by nikspz** [comment]
@supervik Do you want to be assigned for this bounty?

**Comment by supervik** [comment]
> @supervik Do you want to be assigned for this bounty?
Yes, please. Thanks.

**Comment by nikspz** [comment]
Assigning this issue to @supervik  . Thank you for your contribution!

**Comment by carlitogetaladajr** [comment]
@supervik , please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by nikspz** [comment]
Closing this ticket as Paid. 
Fix has been deployed to development branch and will be available on the next release version 1.12.0.
