### ISSUE TITLE
Filled order delay only works if both sides of multi-level order book filled

### ISSUE THREAD

**Issue by hlian188** [hummingbot/hummingbot#5779]
**Describe the bug**
Filled order delay only works if all non-hanging levels of order book are filled for avellaneda market making strategy. I would expect the delay to occur after every fill of a non-hanging order. If this is not possible, please make this an optional parameter at least.

**Steps To Reproduce**
I've attached my config file. All I did was import and run the strat
...

**Release version**
1.8

**Attachments**
[conf_avellaneda_market_making_eth1.zip](https://github.com/hummingbot/hummingbot/files/9719004/conf_avellaneda_market_making_eth1.zip)

Attached is my config file

**Comment by cardosofede** [comment]
can you provide a log file?
the code seems ok: 
![image](https://user-images.githubusercontent.com/36869960/194901635-4ae84d4b-9ec4-420d-b241-7bfc2ac5712e.png)

**Comment by nikspz** [comment]
on development 1.9.0
using config similar to user's config
bot didn't wait for filled order delay

log and config files:
[issue5779.zip](https://github.com/hummingbot/hummingbot/files/9760111/issue5779.zip)
[logs_issue5779.log](https://github.com/hummingbot/hummingbot/files/9760113/logs_issue5779.log)

![issue5779 hanging order multiple levels2](https://user-images.githubusercontent.com/83953535/195210763-2832cc03-feda-4327-bce6-bb76d9aea9ff.gif)

**Comment by rapcmia** [comment]
Hi @hlian188 good day to you.
Please be advised that the current behavior that you have observed is the expected behavior for `filled_order_delay` parameter. It would not worked for multiple order filled events atm but instead you can create a thread on our [Hummingbot forum](https://forum.hummingbot.org/) so our community can have a look with your idea and create an [feature request ticket ](https://github.com/hummingbot/hummingbot/issues/new/choose)

Closing ticket for now, Thank you
