### ISSUE TITLE
Upgrade Huobi Spot to v2.1

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5793]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by litepresence** [comment]
I am interested in these 4 spot Connector upgrades to v2.1; I would like to do them as a group:

issues [5791](https://github.com/hummingbot/hummingbot/issues/5791), [5792](https://github.com/hummingbot/hummingbot/issues/5792), [5793](https://github.com/hummingbot/hummingbot/issues/5793), [5794](https://github.com/hummingbot/hummingbot/issues/5794):

ByBit
Ascendex
Huobi
HitBTC


I am familiar with both dev on Hummingbot side post 2.1 (I have an open pull for Graphene DEX Connector) and I have extensive API experience at many CEX exchanges since 2013.   

How can I schedule an interview?

**Comment by drewUCL** [comment]
Also interested in all connectors - how do schedule an interview? No discord. 

I have worked at the top HFT firms in the world and been doing ultra low latency crypto trading (spot and futures) over the past 5 years. Expert low latency C++, Java, and Python developer.

**Comment by JeremyKono** [comment]
Hi @litepresence, will be assigning this connector to you. Thank you for your contribution!

**Comment by JeremyKono** [comment]
Hi @litepresence, are you still interested in working on the improvement? When can we get an update?

**Comment by JeremyKono** [comment]
Will be reassigning this bounty to another developer as the current developer hasn't responded

**Comment by yancong001** [comment]
I would like to be assigned this ticket

**Comment by dennisocana** [comment]
We (CoinAlpha) would like to be assigned to this bounty.

**Comment by JeremyKono** [comment]
Hi @yancong001, you can only have 1 connector to work on per bounty. As I can see you are working on Bybit at the moment. Will be assigning this bounty to CoinAlpha.

**Comment by JeremyKono** [comment]
This bounty has been paid. Thanks!

**Comment by nikspz** [comment]
Hi, closing this enhancement as it has been marked as paid. Thank you for your contribution!
