### ISSUE TITLE
UniswapLP strategy bot stuck in loop, failing to create WETH-USDC pool

### ISSUE THREAD

**Issue by berchapman** [hummingbot/hummingbot#5864]
**Describe the bug**
uniswap_v3_lp strategy bot is stuck in loop attempting to create WETH-USDC pool, and fails  to create the liquidity pool.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Hummingbot installed from source, on Ubuntu 18.04 LTS
2. Start hummingbot
3. Verify gateway is online
4. Ran `create` (see "create.png" screenshot)
5. Ran `balance` to check balances, verify I have enough WETH, USDC, and ETH (see "balances.png" screenshot)
6. Ran `start` (see "start.png" screenshot)
7. Logs show continuous loop of creating new position, but it never creates, always fails. Uniswap shows no position created,
8. Ran `config` to check configuration (see "config.png" screenshot)
9. Stopped bot
...

**Screenshots**
![config](https://user-images.githubusercontent.com/5395008/200094397-da3ba0d7-953a-4134-a496-a441dff71a05.png)
![create](https://user-images.githubusercontent.com/5395008/200094393-42856b3c-8eb3-4857-91a3-5af678f95e82.png)
![start](https://user-images.githubusercontent.com/5395008/200094395-6890a5ea-6cb5-4e6a-bd81-200718247c4d.png)
![balance](https://user-images.githubusercontent.com/5395008/200094396-8fa419d6-7cf5-4ef6-ab2e-28f45d6bd075.png)

**Release version**
v1.9.0

**Attachments**
[logs_conf_uniswap_v3_lp_v4.log](https://github.com/hummingbot/hummingbot/files/9942650/logs_conf_uniswap_v3_lp_v4.log)
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9942651/logs_hummingbot.log)

Discord username: Shambolaz (Shambolaz#6446)
Initial comment in general > "support" channel: https://discord.com/channels/530578568154054663/563462222878212098/1037453507114041354

**Comment by rapcmia** [comment]
Hi @berchapman good day and apologies on the delay, 
Just wanted to confirm if you tried to change the nodeURL to infura instead of using ankr? 

Incase you want to change it here is the steps to do:
1. Start hummingbot client and make sure gateway is `ONLINE`
2. Run `gateway config ethereum.networks.goerli.nodeURL  insert_infura_nodeurl`
3. Import then start the strategy again

For infura nodeURL you can create one [here](https://app.infura.io/login), let us know if this works for you! :beers:

**Comment by nikspz** [comment]
Closed that issue as resolved by changing NodeURL
