### ISSUE TITLE
not sure bug 

### ISSUE THREAD

**Issue by tomerqueves** [hummingbot/hummingbot#5925]
**Describe the bug**
// A clear and concise description of what the bug is.
im reading the code and folder setup on last line win64 means a absolute path that's invoice c:/user/anuser... 
not sure if ever machines need uses this path but could find not because not all users names marti

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
i was navigate and read code on github. 
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...can't reproduce because runs Ubuntu 

**Screenshots**
// If applicable, add screenshots to help explain your problem.
I'll post and edit the with a capture but is readable on setup and windows file installation at last line 
![Screenshot_20221205_140226_com.github.android.jpg](https://user-images.githubusercontent.com/51311559/205644418-13fc8ae1-099b-459c-a6a5-097dbcc3782b.jpg)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
no one now. was human read code 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
i will do later 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
not sure if its treebtc or tomerqueves but not usually uses discord

**Comment by rapcmia** [comment]
Hi @tomerqueves good day
I can confirm that this is showing on my dev and PRs but this does not affect how the client's expected behavior. My guess for this prefix is that it specifies the directory to put the environment in. I have not experience such issues with it assuming conda just ignores this line when not available.

Closing this ticket for now, else you may want to open a topic from our developer channel on discord. Thank you
