### ISSUE TITLE
Regarding the use of external scripts to stop robots, pending orders are not canceled。

### ISSUE THREAD

**Issue by dongpuxiao** [hummingbot/hummingbot#5931]
Hello, due to certain scenarios and reasons, I cannot call the stop command inside the hummingbot docker to cancel the pending order. 
      I need to call the command to stop hummingbot and cancel the pending order when the host is in fast start mode (currently through docker stop The order is stopped, the pending order is not cancelled), what can I do?

**Comment by rapcmia** [comment]
Hi @dongpuxiao good day to you
I would assume this is possibly related to the external script as most of scripts we tests are working as expected when calling the stop command. While we think this requires further checking, we suggest to use our discord `developer-chat` or `scripts` channel so our community/internal devs can help with this issue. 

Ill be closing this ticket for now however in the event that this is something that requires a ticket due to a bug report, please make use of our bug-report template and add the details/files needed for investigation. Thank you for time! 👍
