### ISSUE TITLE
Pure market strategy doesn't work on empty order book

### ISSUE THREAD

**Issue by Dmdv** [hummingbot/hummingbot#5934]
**Describe the bug**

Pure market strategy doesn't work on empty order book.
I've created a new connector and trying to test it.
Orderbook is empty.

And I've created pure market making strategy which supposed to create orders but failing because
evidently there are no orders and hence no price can be fetched.

Is it a bug or feature remains to the consideration but anyway this is the goal 
of pmm is to define market

```
Order book is empty - no price quote is possible.
Bid orderbook for SELL-USDT is empty.
```

Where `SELL` - is an test token

**Steps To Reproduce**
- Run humming bot
- Use it for the market with empty orderbook
- Create the simplest possible pmm strategy
- Start the strategy 

**Release version**
development branch

**Comment by rapcmia** [comment]
Hi @Dmdv good day
I think this is expected to happen for connector that has empty orderbooks since Pure market making design for spot connectors where the mid price is created based on the price of the top bid/ask order. At some point I also find it to be a good improvement for the strategy which is why I dont find it as bug but rather an improvement/feature. I think its better if you can post a thread to our discord `proposal-discussion` channel so our community can share ideas about it 🙇
