### ISSUE TITLE
Crypto.com - Hummingbot API is outdated

### ISSUE THREAD

**Issue by Alkhalifah-blockchain** [hummingbot/hummingbot#6023]
Hi team,

Crypto dot com exchange has upgraded their API to a the third version a few months ago, and the current connector on Hummingbot is still out of date.

I would like to nominate upgrading the crypto dot com API to avoid delays and ensure optimal execution.

You can find more details about the new API below:
https://static2.crypto.com/exchange/assets/documents/oex-migration-faq.pdf

**Comment by nikspz** [comment]
Duplicated with this issue: 
https://github.com/hummingbot/hummingbot/issues/5868

**Comment by nikspz** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Community bounty related to bronze connector (connector needs API update)

**Comment by nikspz** [comment]
Okay, I will assign you both for the bounty of Crypto.com API , but it will be paid at the one address that you provide.

**Comment by nikspz** [comment]
Assigning @srirambandi and @manibandi for this bounty

**Comment by nikspz** [comment]
Yep, could start now ✅

**Comment by nikspz** [comment]
hi @srirambandi Could you please add any your updates on this bounty?

**Comment by srirambandi** [comment]
@nikspz sorry for the delay. Yes will push our current commits to a draft PR by this Sunday. Still in progress, but from start of next week, our progress will be good. 🙌

**Comment by rapcmia** [comment]
Hi @srirambandi good day to you, 
Can you let us know of any update for the PR? The team is planning to add this update to the next release. Thank you

**Comment by manibandi** [comment]
Hi @rapcmia and @nikspz, sorry in the delay to update soon. We have created a draft PR, where we are pushing the working commits. We'll be done with the connector logic and test it within a week(using Crypto.com sandbox as we don't have keys for main account). And then we'll write the unit tests for it. 

So glad the team has planned for including this in the next release! We'll try to get this merged before time.

**Comment by bonez56** [comment]
I'm deeply saddened to hear that the Crypto.com connector may be removed from Hummingbot due to no HBOT votes this quarter. There are people who use it, I have been using it since 2020 when it was first introduced. There are two gentlemen who took up the bounty offer and are almost finished fixing the code to implement the required connector changes, it would be such a shame to simply stop work and dump the connector from the code. HB team, if you're reading this - please reconsider. I don't hold any HBOT tokens, if I'd known it would have only taken 100k to keep the connector working, I would have personally considered buying the token just to vote.

**Comment by Alkhalifah-blockchain** [comment]
I am willing to vote for maintaining crypto dot com's connector, I have been using it for a while and would love to see it maintained

**Comment by bonez56** [comment]
Me as well, I've been using it since late 2020 and I'll be deeply
disappointed if it is removed from the code.

I don't have any HBOT but if required I would consider obtaining some.

**Comment by nikspz** [comment]
We are closing this bounty since during Epoch 5 CEX Connectors Poll Crypto.com connector not voted with minimum amount for a CEX connector
https://snapshot.org/#/hbot.eth/proposal/0x231e942b5f23b406d409f2b12319891ab3c92605e367f75e56015061e905d56e
Also this bounty not ready after more than 2 month period of development, and developer not fix simple issues shortly / not being responsive.

**Comment by nikspz** [comment]
@Alkhalifah-blockchain @bonez56 If you want crypto.com connector will be added again in the codebase, you will need to create a new Proposal using snapshot.
Please review proposed governance changes here:
https://snapshot.org/#/hbot.eth/proposal/0x63958a27907ef6efa072fc92566f91bcf5df7491523ffcc64ecb47f270df9bcd

**Comment by srirambandi** [comment]
> We are closing this bounty since during Epoch 5 CEX Connectors Poll Crypto.com connector not voted with minimum amount for a CEX connector https://snapshot.org/#/hbot.eth/proposal/0x231e942b5f23b406d409f2b12319891ab3c92605e367f75e56015061e905d56e The PR for removal not-maintained connectors will be ready next week

If this goes for another proposal to be voted in, I can finish unit tests and submit the PR again.

> Also this bounty not ready after more than 2 month period of development, and developer not fix simple issues shortly / not being responsive.

@nikspz what small fixes ami missing, let me know. The connector is ready to be tested on the logic. I even pushed some unit tests, although unit tests are not important for bronze connectors all that much as I've read yesterday in our discord comment. I am genuinely asking what small fixes were we missing?
