### ISSUE TITLE
Docker build for gateway timing out

### ISSUE THREAD

**Issue by zalam003** [hummingbot/hummingbot#6071]
**Describe the bug**
The docker build of gateway-v2 times out.  The image on Docker hub is not functional

**Steps To Reproduce**
Pull hummingbot/gateway-v2 for AMD.  It will fail during pull.

** Fix:
increase timeout by adding following to gateway/Dockerfile

```
 RUN yarn install --network-timeout 1000000
```

**Comment by nikspz** [comment]
@zalam003 Could you please tell your machine type, OS and also bot and gateway installation type? 
It would be nice if you provide more steps on how to reproduce this

we are currently working on a gateway update that will be available on the next release

**Comment by fengtality** [comment]
@zalam003 Thanks for the issue + fix. We're actually moving toward a standalone Gateway repo and changing the installation experience so that it's similar to Hummingbot Docker: https://github.com/hummingbot/gateway. The new DockerHub is https://hub.docker.com/r/hummingbot/gateway. Some things are still WIP but it should mostly work.
