### ISSUE TITLE
amm_arb strategy started, but the status of the strategy is not ready. Please try again later.

### ISSUE THREAD

**Issue by debanjanAqb** [hummingbot/hummingbot#6353]
**Hi Team, I have created amm_arb strategy through docker env. of Hummingbot. I am attaching the screen-shot of its configuration.**
![Screenshot from 2023-06-01 14-58-43](https://github.com/hummingbot/hummingbot/assets/128053922/1de2cc99-86cf-4528-af73-d086c408dc21)
![Screenshot from 2023-06-01 14-51-59](https://github.com/hummingbot/hummingbot/assets/128053922/b4addcb5-7d4e-4aca-afbf-f6b1fac08434)

**I have sufficient balance in my mainnet wallet.**
![Screenshot from 2023-06-01 14-53-27](https://github.com/hummingbot/hummingbot/assets/128053922/51c3992c-2ca6-4a5a-b21c-26496fc32e1e)

**But when I run the start command for running the strategy, I am getting below error.**
![Screenshot from 2023-06-01 15-03-16](https://github.com/hummingbot/hummingbot/assets/128053922/98fe8282-d672-405e-a5e6-8cd58251fe47)
And when I run the status command, it shows me below warning.
![Screenshot from 2023-06-01 15-05-19](https://github.com/hummingbot/hummingbot/assets/128053922/5d94197f-558b-4f1e-b8e5-8f3ffeab5376)

When I am trying to approve the token, I am getting following error.
![Screenshot from 2023-06-01 17-29-42](https://github.com/hummingbot/hummingbot/assets/128053922/faaf25dc-65fd-4bf4-9c2e-38e59c4ae6dd)

**For your reference I am also attaching the screenshot of metamask.**
![Screenshot from 2023-06-01 15-21-40](https://github.com/hummingbot/hummingbot/assets/128053922/cd1867ca-1046-4514-96be-c44053845027)

**Please help me. Thanks in advance for your support.**

**Comment by rapcmia** [comment]
Hi @debanjanAqb good day
Checked latest development branch on docker env and works as expected, it seems that the token you want to use must be approved first which is why this is behavior of the client. 

Token approved:
```
2023-06-05 05:05:36,415 - 1 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-06-05 05:06:11,655 - 1 - hummingbot.client.hummingbot_application - INFO - Connector uniswap Tokens WETH will now be approved for spending for 'uniswap_ethereum_mainnet'.
2023-06-05 05:06:14,917 - 1 - hummingbot.client.hummingbot_application - INFO - Token WETH approval transaction is pending. Transaction hash: 0x0ed605c7cbb5ebea491c75d9b9c9d8787c468bc32627bccaa61b4161910dae66
2023-06-05 05:06:23,260 - 1 - hummingbot.client.hummingbot_application - INFO - Token WETH is approved for spending for 'uniswap' for Wallet: 0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843.
```
- There instances that we need to modify the `gateway config ethereum.gasLimitTransaction` which is currently on `3000000`
- On this test, we change it to `500000`

Run AMM-Arb
![image](https://github.com/hummingbot/hummingbot/assets/73840223/369e4abe-b30b-49da-875e-3e67a69bbb75)

For gateway related issues we suggest to submit a ticket instead to https://github.com/hummingbot/gateway
