### ISSUE TITLE
Fixed grid script - when order book called, logs started to print in the left pane

### ISSUE THREAD

**Issue by mirono** [hummingbot/hummingbot#6522]
### Describe the bug

I run a script. entering order book command.
The order book is printed on the logs part of the UI, and logs started to print in the main (left) part of the screen, and not in the log part. can't return to normal behaviour.

### Steps to reproduce

1.  start --script whatever
2. order book
3. 

### Release version

dev-1.18.0

### Type of installation

Docker

**Comment by nikspz** [comment]
@mirono 
Could't reproduce the behavior you noticed. If you referred to this behavior on the screenshot - that's expected behavior. 
If you want to close order_book you could use:
1. `order_book --close command`
2. Ctrl+B or Ctrl+N to switch tabs

![image](https://github.com/hummingbot/hummingbot/assets/83953535/63798233-db99-414e-9b8d-c1aabf3175c4)
