### ISSUE TITLE
Lost connection binance_us

### ISSUE THREAD

**Issue by Galantek** [hummingbot/hummingbot#6570]
### Describe the bug

Trading on binance.us orders will be placed for a few minutes. Then connection to exchange is lost. And the error is received from binance.com instead of binance.us. Something seems to be calling the default_domain instead of  .us from the config resulting in a lost connection.

}OSError: Error executing request GET https://fapi.binance.com/fapi/v1/time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}

### Steps to reproduce

1. create config
2. set to binance_us
3. start trading
4. wait until error

### Release version

1.19.0

### Type of installation

Docker

### Attach required files

[logs_conf_RLC_USDT_Liquidity_Test.log](https://github.com/hummingbot/hummingbot/files/12642880/logs_conf_RLC_USDT_Liquidity_Test.log)

**Comment by rapcmia** [comment]
Hi @Galantek i dont think you have proper access to `binance.us` due to error of `restricted location..` In the event you still need to have this fix, i would suggest to check if your location is within the allowable areas of the exchange or contact their support for inquiry about it. Else you can try to use connect with `binance` only
