### ISSUE TITLE
Kucoin - Orders created without exchange_order_id

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6974]
### Description

Looking for fix on the reported tickets related to orders created on connector that does not have `exchange_order_id` that causes error on failed to cancel, fetching order update and lost orders.

- [Kucoin - Order canceled and filled at the same time causes failed to cancel, KeyError: 'data'  #6970](https://github.com/hummingbot/hummingbot/issues/6970)
- [Kucoin false order created event #6890](https://github.com/hummingbot/hummingbot/issues/6890)
- [Kucoin lost order error #6968](https://github.com/hummingbot/hummingbot/issues/6968)

### Bounty Criteria

- Investigate the Kucoin issues above which appear related to `exchange_order_id` 
- Create a fix that addresses these issues
- Includes unit tests that checks for the issues found

### Bounty

- Sponsor: Foundation
- Bounty amount: 136,000 HBOT or 500 USDC
- Developer portion: 100%

**Comment by tomasgaudino** [comment]
hi there! i'd like to take this bounty please

**Comment by nikspz** [comment]
Assigned to @tomasgaudino, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
thanks @nikspz ! i'll giving updates this week

**Comment by tomasgaudino** [comment]
PR opened https://github.com/hummingbot/hummingbot/pull/6999

Please follow any discussion on PR conversation

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @tomasgaudino . The fix has been deployed on development branch and hummingbot version 1.28.0
